version: 0.0.1.{build}
image: Visual Studio 2017
platform:
  - Any CPU

configuration:
  - Release


dotnet_csproj:
  patch: true
  file: '**\GenericBuffer.Core.csproj'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'

before_build:
  - nuget restore
  
build:
  verbosity: minimal
  publish_nuget: true                    # package projects with .nuspec files and push to artifacts
  publish_nuget_symbols: true     # generate and publish NuGet symbol packages
  include_nuget_references: true # add -IncludeReferencedProjects option while packaging NuGet artifacts

deploy:
- provider: NuGet
  api_key:
    secure: BX8fMIl1srR8gTFarh3cP8999pcEu9C9O00Wm7y50sxZ1ZqlTK2fUCozjUXF7CU3
  on:
    branch: /release\/[0-9, .]+/