version: 1.1.0.{build}
image: Visual Studio 2017
platform:
  - Any CPU

configuration:
  - Release

before_build:
  - cmd: dotnet --info
  - cmd: dotnet --version
  - cmd: nuget restore

dotnet_csproj:
  patch: true
  file: '**\GenericBuffer.Core.csproj'
  package_version: "{version}"
  assembly_version: "{version}"
  file_version: "{version}"

# build:
#   verbosity: minimal
#   publish_nuget: true # package projects with .nuspec files and push to artifacts
#   publish_nuget_symbols: true # generate and publish NuGet symbol packages
#   include_nuget_references: true # add -IncludeReferencedProjects option while packaging NuGet artifacts

test_script:
  - dotnet test .\GenericBuffer.Tests\GenericBuffer.Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=lcov -p:CoverletOutput=./../lcov.info

build_script:
  - msbuild "C:\projects\genericbuffer\GenericBuffer.sln" /verbosity:minimal /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll"

artifacts:
  - path: ./lcov.info
    name: lcov.info

deploy:
  - provider: NuGet
    api_key:
      secure: BX8fMIl1srR8gTFarh3cP8999pcEu9C9O00Wm7y50sxZ1ZqlTK2fUCozjUXF7CU3
    on:
      branch: /release\/[0-9, .]+/
