name: Build

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.301
      - name: ls
        run: ls
      - name: pwd
        run: pwd
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test ./GenericBuffer.Tests/GenericBuffer.Tests.csproj
      - name: Build
        run: dotnet publish --configuration Release --no-restore --framework netstandard2.0
